### ISSUE TITLE
log_parser not extracting information for all assemblies

### ISSUE THREAD

**Issue by jshanUCI** [Ivanmugu/log_parser#1]
log_parser is not extracting the following information for all of the assemblies: Depth | Starting_gene | Position | Strand | Identity | Coverage.

Provided is the output .csv file run on 283 assembled genomes in server 1, sorted based on the size of the molecule.  

[molecules_summary.csv](https://github.com/Ivanmugu/log_parser/files/6299579/molecules_summary.csv)

**Comment by Ivanmugu** [comment]
Hi Jack, thank you for your comment.
The problem was fixed. I did a new version of the program that will give three csv files with the names depth_summary, status_summary, and assemblies_summary. In this new version, you will find all the information that you mentioned in your comment.

Kind regards,
Ivan
